server:
  port: 8600
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anjincai/eureka-config.git
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8100/eureka/,http://peer1:8101/eureka/


